package in.kpmg.cm.repo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import in.kpmg.cm.dto.rsp.HealthcardResponseDto;
import in.kpmg.cm.dto.rsp.IncrementalResponseDto;
import in.kpmg.cm.dto.rsp.PreauthDetailsResponseDto;
import in.kpmg.cm.dto.rsp.PreauthResponseDto;
import in.kpmg.cm.models.AsritCaseModel;

@Repository
public interface IncrementalDataRepo extends JpaRepository <AsritCaseModel, String> {

	@Query(value = "SELECT \r\n"
			+ "    ap.ration_card_no rationCardNo, \r\n"
			+ "    ap.first_name  || ' ' || ap.middle_name || ' ' || ap.last_name AS patientName , \r\n"
			+ "    ap.resident_id residentId,\r\n"
			+ "    ap.uhidvalue uhidValue, \r\n"
			+ "    ap.age age, \r\n"
			+ "    CASE WHEN ap.gender = 'M' THEN 'Male' WHEN ap.gender = 'F' THEN 'Female' END AS gender , \r\n"
			+ "    am.cmb_dtl_name AS caste,\r\n"
			+ "    ac.case_id caseId,\r\n"
			+ "    dist.lgd_code AS districtCode,\r\n"
			+ "    dist.loc_name AS patientDistrict, \r\n"
			+ "    man.lgd_code AS mandalCode,\r\n"
			+ "    man.loc_name AS mandal,\r\n"
			+ "    ham.lgd_code AS hamletCode,\r\n"
			+ "    ham.loc_name AS hamlet, \r\n"
			+ "    vil.lgd_code AS villageCode,\r\n"
			+ "    vil.loc_name AS village,\r\n"
			+ "    sach.lgd_code AS sachCode,\r\n"
			+ "    sach.loc_name AS sachivalayam,\r\n"
			+ "    ac.case_hosp_code caseHospCode, \r\n"
			+ "    ah.hosp_name hospName, \r\n"
			+ "    dis.lgd_code AS hospitalDistCode,\r\n"
			+ "    dis.loc_name AS hospitalDist,\r\n"
			+ "    mand.lgd_code AS hospitalMandalCode,\r\n"
			+ "    mand.loc_name AS hospitalMandal,\r\n"
			+ "    CASE WHEN ah.hosp_type = 'G' THEN 'Government' WHEN ah.hosp_type = 'C' THEN 'Corporate' END AS hospType,\r\n"
			+ "    acs.dis_main_code AS specialityCode,adm.dis_main_name AS specialityName,\r\n"
			+ "    LISTAGG(acs.surgery_code, ', ') WITHIN GROUP (ORDER BY acs.surgery_code) AS procedureCodes, \r\n"
			+ "    LISTAGG(as1.surgery_desc, ', ') WITHIN GROUP (ORDER BY acs.surgery_code) AS procedureNames,\r\n"
			+ "    ac.actual_clm_sub_dt AS claimSubmittedDate,\r\n"
			+ "    ac.cs_clm_bill_amt AS claimRaisedAmt,\r\n"
			+ "    ac.cs_preauth_dt preauthInitDt,\r\n"
			+ "        CASE \r\n"
			+ "        WHEN ac.case_status IN (SELECT status_id FROM asrim_case_status_grp WHERE group_id = 'CD17') \r\n"
			+ "        THEN ac.cs_apprv_rej_dt \r\n"
			+ "    END AS preauthApprvDt,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN ac.cs_apprv_rej_dt IS NOT NULL AND ag.group_id = 'CD17'\r\n"
			+ "        THEN DECODE(acc.case_cmo_aprv_amt, NULL, \r\n"
			+ "                   DECODE(acc.case_ceo_aprv_amt, NULL, acc.case_trust_aprv_amt, 0, acc.case_trust_aprv_amt, acc.case_ceo_aprv_amt),\r\n"
			+ "                   acc.case_cmo_aprv_amt)\r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS preauthAmount,\r\n"
			+ "    ac.cs_sbh_dt AS claimPaidDate,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL AND acc.case_ceo_aprv_amt IS NULL \r\n"
			+ "        THEN acc.case_eo_aprv_amt \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL \r\n"
			+ "        THEN acc.case_ceo_aprv_amt \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS claimsPaidAmount\r\n"
			+ "FROM asrit_case ac\r\n"
			+ "LEFT JOIN asrit_patient ap ON ac.case_patient_no = ap.patient_id\r\n"
			+ "LEFT JOIN asrit_case_claim acc ON ac.case_id = acc.case_id\r\n"
			+ "LEFT JOIN asrit_case_surgery acs ON acs.case_id = ac.case_id\r\n"
			+ "LEFT JOIN asrim_case_status_grp ag ON ac.case_status = ag.status_id\r\n"
			+ "LEFT JOIN asrim_disease_main adm ON adm.dis_main_id = acs.dis_main_code\r\n"
			+ "LEFT JOIN asrim_surgery as1 ON as1.surgery_id = acs.surgery_code and as1.dis_main_id = acs.dis_main_code and as1.dis_sub_id = acs.dis_sub_code\r\n"
			+ "LEFT JOIN asrim_hospitals ah ON ah.hosp_id = ac.case_hosp_code\r\n"
			+ "LEFT JOIN asrit_empnl_hospinfo aeh ON ah.HOSP_EMPNL_REF_NUM = aeh.hospinfo_id\r\n"
			+ "LEFT JOIN asrim_locations dist ON dist.loc_id = ap.c_district_code\r\n"
			+ "LEFT JOIN asrim_locations ham ON ham.loc_id = ap.c_hamlet_code\r\n"
			+ "LEFT JOIN asrim_locations vil ON vil.loc_id = ap.c_village_code\r\n"
			+ "LEFT JOIN asrim_locations man ON man.loc_id = ap.c_mandal_code\r\n"
			+ "LEFT JOIN asrim_locations sach ON sach.loc_id = ap.c_sachi_code\r\n"
			+ "LEFT JOIN asrim_locations dis ON dis.loc_id = ah.dist_id\r\n"
			+ "LEFT JOIN asrim_locations mand ON mand.loc_id = aeh.mandal\r\n"
			+ "LEFT JOIN asrim_combo am ON am.cmb_dtl_id = ap.caste\r\n"
			+ "WHERE ag.group_id = 'CD17' -- and ac.case_id = '6112'\r\n"
			+ "GROUP BY \r\n"
			+ "    ap.ration_card_no, \r\n"
			+ "    ap.first_name, ap.middle_name, ap.last_name, \r\n"
			+ "    ap.resident_id, ap.uhidvalue, ap.age, \r\n"
			+ "    ap.gender, am.cmb_dtl_name, \r\n"
			+ "    dist.lgd_code, dist.loc_name, \r\n"
			+ "    man.lgd_code, man.loc_name, \r\n"
			+ "    ham.lgd_code, ham.loc_name, \r\n"
			+ "    vil.lgd_code, vil.loc_name, \r\n"
			+ "    sach.lgd_code, sach.loc_name, \r\n"
			+ "    ac.case_id, \r\n"
			+ "    ac.case_hosp_code, \r\n"
			+ "    ah.hosp_name,  \r\n"
			+ "    dis.lgd_code, dis.loc_name,\r\n"
			+ "    mand.lgd_code, mand.loc_name,\r\n"
			+ "    ah.hosp_type, \r\n"
			+ "    acs.dis_main_code, \r\n"
			+ "    ac.case_status, ag.group_id,\r\n"
			+ "    ac.cs_apprv_rej_dt, \r\n"
			+ "    acc.case_ceo_aprv_amt, \r\n"
			+ "    acc.case_eo_aprv_amt, \r\n"
			+ "    acc.case_trust_aprv_amt,adm.dis_main_name, \r\n"
			+ "    acc.case_cmo_aprv_amt, \r\n"
			+ "    ac.cs_clm_bill_amt,ac.cs_preauth_dt,\r\n"
			+ "    ac.cs_sbh_dt,\r\n"
			+ "    ac.actual_clm_sub_dt", nativeQuery = true)
	List<IncrementalResponseDto> getIncrementalData();

	
	@Query(value ="SELECT DISTINCT \r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') \r\n"
			+ "        || '-' || (to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') + 1) AS financialYear,\r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'Month') AS Month,\r\n"
			+ "    ac.case_hosp_code AS caseHospCode, \r\n"
			+ "    ah.hosp_name AS hospName, \r\n"
			+ "    dis.lgd_code AS hospitalDistCode,\r\n"
			+ "    dis.loc_name AS hospitalDist,\r\n"
			+ "    mand.lgd_code AS hospitalMandalCode,\r\n"
			+ "    mand.loc_name AS hospitalMandal,\r\n"
			+ "    CASE WHEN ah.hosp_type = 'G' THEN 'Government' WHEN ah.hosp_type = 'C' THEN 'Corporate' END AS hospType,\r\n"
			+ "    count(distinct ac.case_id) AS caseCount,\r\n"
			+ "    count(distinct acs.dis_main_code) specialityCode,\r\n"
			+ "    case when to_date(ac.cs_dis_dt) is not null then count(ac.case_id) end as noOfDischarges,\r\n"
			+ "    case when ac.case_status = 'CD125' then count(ac.case_id) end as totalClaimsApproved,\r\n"
			+ "--    count(acs.surgery_code) procedure_codes,\r\n"
			+ "--    count(LISTAGG(acs.surgery_code, ', ') WITHIN GROUP (ORDER BY acs.surgery_code)) AS procedure_codes\r\n"
			+ "    sum(CASE \r\n"
			+ "        WHEN ac.cs_apprv_rej_dt IS NOT NULL AND ag.group_id = 'CD17'\r\n"
			+ "        THEN DECODE(acc.case_cmo_aprv_amt, NULL, \r\n"
			+ "                   DECODE(acc.case_ceo_aprv_amt, NULL, acc.case_trust_aprv_amt, 0, acc.case_trust_aprv_amt, acc.case_ceo_aprv_amt),\r\n"
			+ "                   acc.case_cmo_aprv_amt)\r\n"
			+ "        ELSE 0 \r\n"
			+ "    END) AS preauthApprovedAmount,\r\n"
			+ "    sum(CASE \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL AND acc.case_ceo_aprv_amt IS NULL \r\n"
			+ "        THEN acc.case_eo_aprv_amt \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL \r\n"
			+ "        THEN acc.case_ceo_aprv_amt \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END) AS claimsPaidAmount\r\n"
			+ "FROM asrit_case ac\r\n"
			+ "LEFT JOIN asrit_patient ap ON ac.case_patient_no = ap.patient_id\r\n"
			+ "LEFT JOIN asrit_case_claim acc ON ac.case_id = acc.case_id\r\n"
			+ "JOIN asrit_case_surgery acs ON acs.case_id = ac.case_id\r\n"
			+ "LEFT JOIN asrim_case_status_grp ag ON ac.case_status = ag.status_id\r\n"
			+ "LEFT JOIN asrim_hospitals ah ON ah.hosp_id = ac.case_hosp_code\r\n"
			+ "LEFT JOIN asrit_empnl_hospinfo aeh ON ah.HOSP_EMPNL_REF_NUM = aeh.hospinfo_id\r\n"
			+ "LEFT JOIN asrim_locations dis ON dis.loc_id = ah.dist_id\r\n"
			+ "LEFT JOIN asrim_locations mand ON mand.loc_id = aeh.mandal\r\n"
			+ "LEFT JOIN asrim_combo am ON am.cmb_dtl_id = ap.caste\r\n"
			+ "WHERE ag.group_id = 'CD17' \r\n"
			+ "GROUP BY \r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') \r\n"
			+ "    || '-' || (to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') + 1),\r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'Month'),\r\n"
			+ "    ac.case_hosp_code, ac.case_status,\r\n"
			+ "    ah.hosp_name, ac.cs_dis_dt,\r\n"
			+ "    dis.lgd_code, dis.loc_name,\r\n"
			+ "    mand.lgd_code, mand.loc_name,\r\n"
			+ "    ah.hosp_type,\r\n"
			+ "    ag.group_id\r\n"
			+ "ORDER BY \r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') \r\n"
			+ "        || '-' || (to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') + 1) ASC,\r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'Month') ASC",nativeQuery = true)
	List<PreauthResponseDto> getPreauthStatisticsData();
	
	@Query(value ="WITH locations AS (\r\n"
			+ "    SELECT\r\n"
			+ "        loc_id,\r\n"
			+ "        loc_name,\r\n"
			+ "        loc_hdr_id\r\n"
			+ "    FROM\r\n"
			+ "        asrim_locations\r\n"
			+ "    WHERE\r\n"
			+ "        active_yn = 'Y'\r\n"
			+ "        AND   (loc_hdr_id = 'LH6' OR loc_hdr_id = 'LH7' OR loc_hdr_id = 'LH10')\r\n"
			+ "        AND   (loc_state_val = '6' OR loc_hdr_id IN ('LH7','LH10')\r\n"
			+ "        )),\r\n"
			+ "skj_data AS (\r\n"
			+ "    SELECT\r\n"
			+ "        a.district AS districtCode,\r\n"
			+ "        b.loc_name AS districtName,\r\n"
			+ "        c.loc_id AS mandalCode,\r\n"
			+ "        c.loc_name AS mandalName,\r\n"
			+ "        a.secretary_code secretaryCode,\r\n"
			+ "        d.loc_name AS secretaryName,\r\n"
			+ "        COUNT(DISTINCT a.householdcardno) AS noOfHealthCards,\r\n"
			+ "        COUNT(*) AS noOfBeneficiaries\r\n"
			+ "    FROM\r\n"
			+ "        asrit_family_cs_ap a\r\n"
			+ "        JOIN asrit_patient_cs_ap aca ON a.householdcardno = aca.householdcardno\r\n"
			+ "        JOIN locations b ON a.district = b.loc_id\r\n"
			+ "                            AND b.loc_hdr_id = 'LH6'\r\n"
			+ "        JOIN locations c ON a.mandal = c.loc_id\r\n"
			+ "                            AND c.loc_hdr_id = 'LH7'\r\n"
			+ "        JOIN locations d ON a.secretary_code = d.loc_id\r\n"
			+ "                            AND d.loc_hdr_id = 'LH10'\r\n"
			+ "    GROUP BY\r\n"
			+ "        a.district,\r\n"
			+ "        b.loc_name,\r\n"
			+ "        c.loc_id,\r\n"
			+ "        c.loc_name,\r\n"
			+ "        a.secretary_code,\r\n"
			+ "        d.loc_name\r\n"
			+ "    UNION ALL\r\n"
			+ "    SELECT\r\n"
			+ "        a.district_id AS districtCode,\r\n"
			+ "        b.loc_name AS districtName,\r\n"
			+ "        aja.mandal AS mandalCode,\r\n"
			+ "        c.loc_name AS mandalName,\r\n"
			+ "        a.secretary_code AS secretaryCode,\r\n"
			+ "        d.loc_name AS secretaryName,\r\n"
			+ "        COUNT(DISTINCT a.temp_card_num) AS noOfHealthCards,\r\n"
			+ "        COUNT(*) AS noOfBeneficiaries\r\n"
			+ "    FROM\r\n"
			+ "        asrit_janmabhoomi_family a\r\n"
			+ "        JOIN asrit_janmabhoomi_patient aja ON a.temp_card_num = aja.temp_card_num\r\n"
			+ "        JOIN locations b ON a.district_id = b.loc_id\r\n"
			+ "                            AND b.loc_hdr_id = 'LH6'\r\n"
			+ "        JOIN locations c ON aja.mandal = c.loc_id\r\n"
			+ "                            AND c.loc_hdr_id = 'LH7'\r\n"
			+ "        JOIN locations d ON a.secretary_code = d.loc_id\r\n"
			+ "                            AND d.loc_hdr_id = 'LH10'\r\n"
			+ "    GROUP BY\r\n"
			+ "        a.district_id,\r\n"
			+ "        b.loc_name,\r\n"
			+ "        aja.mandal,\r\n"
			+ "        c.loc_name,\r\n"
			+ "        a.secretary_code,\r\n"
			+ "        d.loc_name\r\n"
			+ "    UNION ALL\r\n"
			+ "    SELECT\r\n"
			+ "        apa.district_id AS districtCode,\r\n"
			+ "        b.loc_name AS districtName,\r\n"
			+ "        apa.mandal_id AS mandalCode,\r\n"
			+ "        c.loc_name AS mandalName,\r\n"
			+ "        a.secretary_code AS secretaryCode,\r\n"
			+ "        d.loc_name AS secretaryName,\r\n"
			+ "        COUNT(DISTINCT a.temp_card_num) AS noOfHealthCards,\r\n"
			+ "        COUNT(*) AS noOfBeneficiaries\r\n"
			+ "    FROM\r\n"
			+ "        asrit_tap_family_ap a\r\n"
			+ "        JOIN asrit_tap_patient_ap apa ON a.temp_card_num = apa.temp_card_num\r\n"
			+ "        JOIN locations b ON apa.district_id = b.loc_id\r\n"
			+ "                            AND b.loc_hdr_id = 'LH6'\r\n"
			+ "        JOIN locations c ON apa.mandal_id = c.loc_id\r\n"
			+ "                            AND c.loc_hdr_id = 'LH7'\r\n"
			+ "        JOIN locations d ON a.secretary_code = d.loc_id\r\n"
			+ "                            AND d.loc_hdr_id = 'LH10'\r\n"
			+ "    GROUP BY\r\n"
			+ "        apa.district_id,\r\n"
			+ "        b.loc_name,\r\n"
			+ "        apa.mandal_id,\r\n"
			+ "        c.loc_name,\r\n"
			+ "        a.secretary_code,\r\n"
			+ "        d.loc_name\r\n"
			+ ") SELECT\r\n"
			+ "    districtCode,\r\n"
			+ "    districtName,\r\n"
			+ "    mandalCode,\r\n"
			+ "    mandalName,\r\n"
			+ "    secretaryCode,\r\n"
			+ "    secretaryName,\r\n"
			+ "    SUM(noOfHealthCards) AS noOfHealthCards,\r\n"
			+ "    SUM(noOfBeneficiaries) AS noOfBeneficiaries\r\n"
			+ "  FROM\r\n"
			+ "    skj_data\r\n"
			+ "GROUP BY\r\n"
			+ "    districtCode,\r\n"
			+ "    districtName,\r\n"
			+ "    mandalCode,\r\n"
			+ "    mandalName,\r\n"
			+ "    secretaryCode,\r\n"
			+ "    secretaryName\r\n"
			+ "ORDER BY \r\n"
			+ "    districtName,\r\n"
			+ "    mandalName"
			,nativeQuery = true)
	List<HealthcardResponseDto> getHealthCardData();

	@Query(value ="SELECT \r\n"
			+ "    (select current_date from dual) presentDate, \r\n"
			+ "    AH.DIST_ID as districtCode,\r\n"
			+ "    al.loc_name districtName,\r\n"
			+ "    aeh.mandal mandalCode,\r\n"
			+ "    al1.loc_name mandalName,\r\n"
			+ "    ah.hosp_id hospitalCode,\r\n"
			+ "    ah.hosp_name hospitalName,\r\n"
			+ "    case when ah.hosp_type = 'C' then 'Corporate' else 'Government' end as hospitalCategory,\r\n"
			+ "    acs.dis_main_code specialityCode,\r\n"
			+ "    adm.dis_main_name specialityName, \r\n"
			+ "    case when ac.case_status in ('CD81','CD84','CD1985','CD3017','CD1961','CD1504') then count(ac.case_id)\r\n"
			+ "    end as totalPreauthsApproved,\r\n"
			+ "    sum(DECODE(acc.case_cmo_aprv_amt,NULL, \r\n"
			+ "(DECODE(acc.case_ceo_aprv_amt,NULL,acc.case_trust_aprv_amt,0,acc.case_trust_aprv_amt,acc.case_ceo_aprv_amt)\r\n"
			+ "),acc.case_cmo_aprv_amt)) as totalPreauthApprovedAmount,\r\n"
			+ "case when ac.case_status = 'CD125' then count(ac.case_id) end as totalClaimsApproved,\r\n"
			+ "sum(NVL(CASe WHEN acc.case_ceo_aprv_amt IS NULL THEN acc.case_eo_aprv_amt \r\n"
			+ "else acc.case_ceo_aprv_amt END, 0)) AS totalClaimsApprovedAmount,\r\n"
			+ "case when to_date(ac.cs_dis_dt) is not null then count(ac.case_id) end as noOfDischarges\r\n"
			+ "     FROM asrit_case ac\r\n"
			+ "     left join asrit_case_claim acc on ac.case_id = acc.case_id\r\n"
			+ "     left join asrit_audit aa on aa.case_id = ac.case_id\r\n"
			+ "     left join asrit_case_surgery acs on acs.case_id = ac.case_id\r\n"
			+ "     left join ASRIM_HOSPITALS ah on ac.case_hosp_code = ah.hosp_id\r\n"
			+ "     left join asrit_empnl_hospinfo aeh on aeh.hospinfo_id = ah.hosp_empnl_ref_num\r\n"
			+ "     left join asrim_locations al on al.loc_id = ah.dist_id\r\n"
			+ "     left join asrim_disease_main adm on adm.dis_main_id = acs.dis_main_code\r\n"
			+ "     left join asrim_locations al1 on al1.loc_id = aeh.mandal\r\n"
			+ "     where to_date(aa.crt_dt) = to_date(current_date)\r\n"
			+ "group by\r\n"
			+ "    AH.DIST_ID,\r\n"
			+ "    al.loc_name,\r\n"
			+ "    aeh.mandal,\r\n"
			+ "    al1.loc_name,\r\n"
			+ "    ah.hosp_id,\r\n"
			+ "    ah.hosp_name,\r\n"
			+ "    case when ah.hosp_type = 'C' then 'Corporate' else 'Government' end,\r\n"
			+ "    acs.dis_main_code,\r\n"
			+ "    adm.dis_main_name,\r\n"
			+ "    ac.case_status,\r\n"
			+ "    to_date(ac.cs_dis_dt)",nativeQuery = true)
	List<PreauthDetailsResponseDto> getPreauthDetailsData();
}
