package in.kpmg.cm.repo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import in.kpmg.cm.dto.rsp.HealthcardResponseDto;
import in.kpmg.cm.dto.rsp.HospitalDto;
import in.kpmg.cm.dto.rsp.IncrementalResponseDto;
import in.kpmg.cm.dto.rsp.PackagesDto;
import in.kpmg.cm.dto.rsp.PreauthDetailsResponseDto;
import in.kpmg.cm.dto.rsp.PreauthResponseDto;
import in.kpmg.cm.models.AsritCaseModel;

@Repository
public interface IncrementalDataRepo extends JpaRepository <AsritCaseModel, String> {

	@Query(value = "SELECT \r\n"
			+ "    ap.ration_card_no rationCardNo, \r\n"
			+ "    ap.first_name  || ' ' || ap.middle_name || ' ' || ap.last_name AS patientName , \r\n"
			+ "    ap.resident_id residentId,\r\n"
			+ "    ap.uhidvalue uhidValue, \r\n"
			+ "    ap.age age, \r\n"
			+ "    CASE WHEN ap.gender = 'M' THEN 'Male' WHEN ap.gender = 'F' THEN 'Female' END AS gender , \r\n"
			+ "    am.cmb_dtl_name AS caste,\r\n"
			+ "    ac.case_id caseId,\r\n"
			+ "    dist.lgd_code AS districtCode,\r\n"
			+ "    dist.loc_name AS patientDistrict, \r\n"
			+ "    man.lgd_code AS mandalCode,\r\n"
			+ "    man.loc_name AS mandal,\r\n"
			+ "    ham.lgd_code AS hamletCode,\r\n"
			+ "    ham.loc_name AS hamlet, \r\n"
			+ "    vil.lgd_code AS villageCode,\r\n"
			+ "    vil.loc_name AS village,\r\n"
			+ "    sach.lgd_code AS sachCode,\r\n"
			+ "    sach.loc_name AS sachivalayam,\r\n"
			+ "    ac.case_hosp_code caseHospCode, \r\n"
			+ "    ah.hosp_name hospName, \r\n"
			+ "    dis.lgd_code AS hospitalDistCode,\r\n"
			+ "    dis.loc_name AS hospitalDist,\r\n"
			+ "    mand.lgd_code AS hospitalMandalCode,\r\n"
			+ "    mand.loc_name AS hospitalMandal,\r\n"
			+ "    CASE WHEN ah.hosp_type = 'G' THEN 'Government' WHEN ah.hosp_type = 'C' THEN 'Corporate' END AS hospType,\r\n"
			+ "    acs.dis_main_code AS specialityCode,adm.dis_main_name AS specialityName,\r\n"
			+ "    LISTAGG(acs.surgery_code, ', ') WITHIN GROUP (ORDER BY acs.surgery_code) AS procedureCodes, \r\n"
			+ "    LISTAGG(as1.surgery_desc, ', ') WITHIN GROUP (ORDER BY acs.surgery_code) AS procedureNames,\r\n"
			+ "    ac.actual_clm_sub_dt AS claimSubmittedDate,\r\n"
			+ "    ac.cs_clm_bill_amt AS claimRaisedAmt,\r\n"
			+ "    ac.cs_preauth_dt preauthInitDt,\r\n"
			+ "        CASE \r\n"
			+ "        WHEN ac.case_status IN (SELECT status_id FROM asrim_case_status_grp WHERE group_id = 'CD17') \r\n"
			+ "        THEN ac.cs_apprv_rej_dt \r\n"
			+ "    END AS preauthApprvDt,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN ac.cs_apprv_rej_dt IS NOT NULL AND ag.group_id = 'CD17'\r\n"
			+ "        THEN DECODE(acc.case_cmo_aprv_amt, NULL, \r\n"
			+ "                   DECODE(acc.case_ceo_aprv_amt, NULL, acc.case_trust_aprv_amt, 0, acc.case_trust_aprv_amt, acc.case_ceo_aprv_amt),\r\n"
			+ "                   acc.case_cmo_aprv_amt)\r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS preauthAmount,\r\n"
			+ "    ac.cs_sbh_dt AS claimPaidDate,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL AND acc.case_ceo_aprv_amt IS NULL \r\n"
			+ "        THEN acc.case_eo_aprv_amt \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL \r\n"
			+ "        THEN acc.case_ceo_aprv_amt \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END AS claimsPaidAmount\r\n"
			+ "FROM asrit_case ac\r\n"
			+ "LEFT JOIN asrit_patient ap ON ac.case_patient_no = ap.patient_id\r\n"
			+ "LEFT JOIN asrit_case_claim acc ON ac.case_id = acc.case_id\r\n"
			+ "LEFT JOIN asrit_case_surgery acs ON acs.case_id = ac.case_id\r\n"
			+ "LEFT JOIN asrim_case_status_grp ag ON ac.case_status = ag.status_id\r\n"
			+ "LEFT JOIN asrim_disease_main adm ON adm.dis_main_id = acs.dis_main_code\r\n"
			+ "LEFT JOIN asrim_surgery as1 ON as1.surgery_id = acs.surgery_code and as1.dis_main_id = acs.dis_main_code and as1.dis_sub_id = acs.dis_sub_code\r\n"
			+ "LEFT JOIN asrim_hospitals ah ON ah.hosp_id = ac.case_hosp_code\r\n"
			+ "LEFT JOIN asrit_empnl_hospinfo aeh ON ah.HOSP_EMPNL_REF_NUM = aeh.hospinfo_id\r\n"
			+ "LEFT JOIN asrim_locations dist ON dist.loc_id = ap.c_district_code\r\n"
			+ "LEFT JOIN asrim_locations ham ON ham.loc_id = ap.c_hamlet_code\r\n"
			+ "LEFT JOIN asrim_locations vil ON vil.loc_id = ap.c_village_code\r\n"
			+ "LEFT JOIN asrim_locations man ON man.loc_id = ap.c_mandal_code\r\n"
			+ "LEFT JOIN asrim_locations sach ON sach.loc_id = ap.c_sachi_code\r\n"
			+ "LEFT JOIN asrim_locations dis ON dis.loc_id = ah.dist_id\r\n"
			+ "LEFT JOIN asrim_locations mand ON mand.loc_id = aeh.mandal\r\n"
			+ "LEFT JOIN asrim_combo am ON am.cmb_dtl_id = ap.caste\r\n"
			+ "WHERE ag.group_id = 'CD17' -- and ac.case_id = '6112'\r\n"
			+ "GROUP BY \r\n"
			+ "    ap.ration_card_no, \r\n"
			+ "    ap.first_name, ap.middle_name, ap.last_name, \r\n"
			+ "    ap.resident_id, ap.uhidvalue, ap.age, \r\n"
			+ "    ap.gender, am.cmb_dtl_name, \r\n"
			+ "    dist.lgd_code, dist.loc_name, \r\n"
			+ "    man.lgd_code, man.loc_name, \r\n"
			+ "    ham.lgd_code, ham.loc_name, \r\n"
			+ "    vil.lgd_code, vil.loc_name, \r\n"
			+ "    sach.lgd_code, sach.loc_name, \r\n"
			+ "    ac.case_id, \r\n"
			+ "    ac.case_hosp_code, \r\n"
			+ "    ah.hosp_name,  \r\n"
			+ "    dis.lgd_code, dis.loc_name,\r\n"
			+ "    mand.lgd_code, mand.loc_name,\r\n"
			+ "    ah.hosp_type, \r\n"
			+ "    acs.dis_main_code, \r\n"
			+ "    ac.case_status, ag.group_id,\r\n"
			+ "    ac.cs_apprv_rej_dt, \r\n"
			+ "    acc.case_ceo_aprv_amt, \r\n"
			+ "    acc.case_eo_aprv_amt, \r\n"
			+ "    acc.case_trust_aprv_amt,adm.dis_main_name, \r\n"
			+ "    acc.case_cmo_aprv_amt, \r\n"
			+ "    ac.cs_clm_bill_amt,ac.cs_preauth_dt,\r\n"
			+ "    ac.cs_sbh_dt,\r\n"
			+ "    ac.actual_clm_sub_dt", nativeQuery = true)
	List<IncrementalResponseDto> getIncrementalData();
	
	@Query(value="SELECT ah.hosp_id AS hospId, ah.hosp_name AS hospName, ah.hosp_disp_code AS hsCode, CASE WHEN ah.hosp_type = 'G'\r\n"
			+ "				 THEN 'Government' ELSE 'Corporate' END AS hospType, ah.hosp_addr1 || ' ' || ah.hosp_addr2 ||\r\n"
			+ "				 ' ' || ah.hosp_addr3 AS hospitalAddress, al.lgd_code AS stateId, al.loc_name AS stateName, \r\n"
			+ "				DIS.LGD_CODE AS districtCode, DIS.LOC_NAME AS districtName, mand.lgd_code AS \r\n"
			+ "				hospitalMandalCode, mand.loc_name AS hospitalMandal, aeh.ge_code_latitude AS geCodeLatitude, aeh.ge_code_longitude AS geCodeLongitude,\r\n"
			+ "				 (SELECT MAX(au.cug) FROM asrim_users au LEFT JOIN asrim_mit_users anu ON au.user_id = anu.user_id \r\n"
			+ "				WHERE anu.hosp_id = ah.hosp_id AND user_role = 'CD10'AND au.ACTIVE_YN = 'Y' AND eff_end_dt IS NULL)\r\n"
			+ "				 mithraContact, ah.hosp_contact_no AS hospContactNo, (SELECT LISTAGG(ash.speciality_id, ',') WITHIN GROUP \r\n"
			+ "				(ORDER BY ash.speciality_id) FROM asrim_hosp_speciality ash WHERE ash.hosp_id = ah.hosp_id AND\r\n"
			+ "				 ash.phase_id=6 AND ash.renewal = 10 AND ash.is_active_flg = 'Y') AS specialties FROM \r\n"
			+ "				asrim_hospitals ah LEFT JOIN asrit_empnl_hospinfo aeh ON ah.HOSP_EMPNL_REF_NUM = aeh.hospinfo_id \r\n"
			+ "				LEFT JOIN asrim_locations DIS ON ah.dist_id = DIS.LOC_ID LEFT JOIN asrim_locations mand ON \r\n"
			+ "				mand.loc_id = aeh.mandal LEFT JOIN asrim_locations al ON al.loc_id = dis.loc_parnt_id WHERE \r\n"
			+ "				ah.hosp_active_yn = 'Y'", nativeQuery = true)
	List<HospitalDto> findHospitals();
	
	@Query(value="select adm.dis_main_id surgeryCode, ADM.DIS_MAIN_NAME surgeryName, as1.surgery_id\r\n"
			+ "				 procedureCode, AS1.SURGERY_DESC procedureName, as1.proc_type procedureType, case when\r\n"
			+ "				 upper(as1.dis_main_id) like 'S%' then 'Surgical' when upper(as1.dis_main_id) like 'M%' \r\n"
			+ "				then 'Medical' end as treatmentType, CASE WHEN EXISTS (SELECT 1 FROM asrim_surg_phase asp2\r\n"
			+ "				 WHERE asp2.surg_id = as1.surgery_id AND asp2.renewal = '10' AND asp2.govt_yn = 'Y') THEN\r\n"
			+ "				 'Y' ELSE 'N' END AS reservedCategory, as1.surgery_amt procedureAmount,as1.postops_amt \r\n"
			+ "				aasaraAmount from asrim_disease_main adm left join asrim_surgery as1 on as1.dis_main_id = \r\n"
			+ "				adm.dis_main_id left join asrim_surg_phase asp on asp.surg_id = as1.surgery_id where \r\n"
			+ "				asp.phase_id = 6 and asp.renewal = 10 order by adm.dis_main_id, as1.surgery_id", nativeQuery=true)
	List<PackagesDto> findPackages();

	
	@Query(value ="SELECT DISTINCT \r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') \r\n"
			+ "        || '-' || (to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') + 1) AS financialYear,\r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'Month') AS month,\r\n"
			+ "    ac.case_hosp_code AS caseHospCode, \r\n"
			+ "    ah.hosp_name AS hospName, \r\n"
			+ "    dis.lgd_code AS hospitalDistCode,\r\n"
			+ "    dis.loc_name AS hospitalDist,\r\n"
			+ "    mand.lgd_code AS hospitalMandalCode,\r\n"
			+ "    mand.loc_name AS hospitalMandal,\r\n"
			+ "    CASE \r\n"
			+ "        WHEN ah.hosp_type = 'G' THEN 'Government' \r\n"
			+ "        WHEN ah.hosp_type = 'C' THEN 'Corporate' \r\n"
			+ "    END AS hospType,\r\n"
			+ "    count(distinct acs.dis_main_code) AS specialityCode,\r\n"
			+ "    count(distinct (CASE \r\n"
			+ "        WHEN ac.cs_apprv_rej_dt IS NOT NULL AND ag.group_id = 'CD17' THEN ac.case_id\r\n"
			+ "        ELSE null\r\n"
			+ "    END)) AS totalPreauthsApproved,\r\n"
			+ "    sum(CASE \r\n"
			+ "        WHEN ac.cs_apprv_rej_dt IS NOT NULL AND ag.group_id = 'CD17'\r\n"
			+ "        THEN DECODE(acc.case_cmo_aprv_amt, NULL, \r\n"
			+ "                   DECODE(acc.case_ceo_aprv_amt, NULL, acc.case_trust_aprv_amt, 0, acc.case_trust_aprv_amt, acc.case_ceo_aprv_amt),\r\n"
			+ "                   acc.case_cmo_aprv_amt)\r\n"
			+ "        ELSE 0 \r\n"
			+ "    END) AS preauthApprovedAmount,\r\n"
			+ "    SUM(CASE \r\n"
			+ "        WHEN ac.case_status = 'CD125' THEN 1 \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END) AS totalClaimsApproved,\r\n"
			+ "    sum(CASE \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL AND acc.case_ceo_aprv_amt IS NULL \r\n"
			+ "        THEN acc.case_eo_aprv_amt \r\n"
			+ "        WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL \r\n"
			+ "        THEN acc.case_ceo_aprv_amt \r\n"
			+ "        ELSE 0 \r\n"
			+ "    END) AS claimsPaidAmount\r\n"
			+ "FROM asrit_case ac\r\n"
			+ "LEFT JOIN asrit_patient ap ON ac.case_patient_no = ap.patient_id\r\n"
			+ "LEFT JOIN asrit_case_claim acc ON ac.case_id = acc.case_id\r\n"
			+ "JOIN asrit_case_surgery acs ON acs.case_id = ac.case_id\r\n"
			+ "LEFT JOIN asrim_case_status_grp ag ON ac.case_status = ag.status_id\r\n"
			+ "LEFT JOIN asrim_hospitals ah ON ah.hosp_id = ac.case_hosp_code\r\n"
			+ "LEFT JOIN asrit_empnl_hospinfo aeh ON ah.HOSP_EMPNL_REF_NUM = aeh.hospinfo_id\r\n"
			+ "LEFT JOIN asrim_locations dis ON dis.loc_id = ah.dist_id\r\n"
			+ "LEFT JOIN asrim_locations mand ON mand.loc_id = aeh.mandal\r\n"
			+ "LEFT JOIN asrim_combo am ON am.cmb_dtl_id = ap.caste\r\n"
			+ "WHERE ag.group_id = 'CD17' \r\n"
			+ "GROUP BY \r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') \r\n"
			+ "    || '-' || (to_char(add_months(ac.cs_apprv_rej_dt, -3), 'YYYY') + 1),\r\n"
			+ "    to_char(add_months(ac.cs_apprv_rej_dt, -3), 'Month'),\r\n"
			+ "    ac.case_hosp_code, \r\n"
			+ "    ah.hosp_name,  \r\n"
			+ "    dis.lgd_code, dis.loc_name,\r\n"
			+ "    mand.lgd_code, mand.loc_name,\r\n"
			+ "    ah.hosp_type",nativeQuery = true)
	List<PreauthResponseDto> getPreauthStatisticsData();
	
	@Query(value ="with cte as (\r\n"
			+ "select\r\n"
			+ "apc.district AS districtCode,b.loc_name AS districtName,\r\n"
			+ "COUNT(DISTINCT afc.householdcardno) AS noOfHealthCards,\r\n"
			+ "COUNT(*) AS noOfBeneficiaries\r\n"
			+ "from \r\n"
			+ "ASRIT_FAMILY_CS_AP afc \r\n"
			+ "left join ASRIT_PATIENT_CS_AP apc on afc.householdcardno = apc.householdcardno\r\n"
			+ "left join asrim_locations b ON apc.district = b.loc_id AND b.loc_hdr_id = 'LH6'\r\n"
			+ "where afc.active_yn = 'Y'\r\n"
			+ "GROUP BY\r\n"
			+ "        apc.district,\r\n"
			+ "        b.loc_name\r\n"
			+ "union all\r\n"
			+ "select \r\n"
			+ "ajf.district_id AS districtCode,b.loc_name AS districtName,\r\n"
			+ "COUNT(DISTINCT ajf.temp_card_num) AS noOfHealthCards,\r\n"
			+ "COUNT(*) AS noOfBeneficiaries\r\n"
			+ "from ASRIT_JANMABHOOMI_FAMILY ajf \r\n"
			+ "--left join ASRIT_JANMABHOOMI_PATIENT ajp on ajp.temp_card_num = ajf.temp_card_num\r\n"
			+ "left join asrim_locations b ON ajf.district_id = b.loc_id AND b.loc_hdr_id = 'LH6'\r\n"
			+ "where ajf.active_yn = 'Y'\r\n"
			+ "GROUP BY\r\n"
			+ "        ajf.district_id,\r\n"
			+ "        b.loc_name\r\n"
			+ "union all\r\n"
			+ "select \r\n"
			+ "ajp.district_id AS districtCode,b.loc_name AS districtName,\r\n"
			+ "COUNT(DISTINCT ajf.temp_card_num) AS noOfHealthCards,\r\n"
			+ "COUNT(*) AS noOfBeneficiaries\r\n"
			+ "from ASRIT_TAP_FAMILY_AP ajf \r\n"
			+ "left join ASRIT_TAP_PATIENT_AP ajp on ajp.temp_card_num = ajf.temp_card_num\r\n"
			+ "left join asrim_locations b ON ajp.district_id = b.loc_id AND b.loc_hdr_id = 'LH6'\r\n"
			+ "where ajf.active_yn = 'Y'\r\n"
			+ "GROUP BY\r\n"
			+ "        ajp.district_id,\r\n"
			+ "        b.loc_name)\r\n"
			+ "select * from cte"
			,nativeQuery = true)
	List<HealthcardResponseDto> getHealthCardData();

	@Query(value ="WITH splty AS (\r\n"
			+ "SELECT \r\n"
			+ "DISTINCT acs.case_id, \r\n"
			+ "MIN(acs.dis_main_code) AS dis_main_code\r\n"
			+ "FROM asrit_case_surgery acs\r\n"
			+ "GROUP BY acs.case_id\r\n"
			+ "),\r\n"
			+ "cte AS (\r\n"
			+ "SELECT\r\n"
			+ "DISTINCT \r\n"
			+ "TRUNC(SYSDATE) AS \"DATE\",\r\n"
			+ "ac.case_hosp_code AS caseHospCode,\r\n"
			+ "ah.hosp_name AS hospName,\r\n"
			+ "dis.lgd_code AS hospitalDistCode,\r\n"
			+ "dis.loc_name AS hosptialDist,\r\n"
			+ "mand.lgd_code AS hospitalMandalCode,\r\n"
			+ "mand.loc_name AS hospitalMandal,\r\n"
			+ "splty.dis_main_code AS specialityCode,\r\n"
			+ "CASE\r\n"
			+ "WHEN ah.hosp_type = 'G' THEN 'Government'\r\n"
			+ "WHEN ah.hosp_type = 'C' THEN 'Corporate'\r\n"
			+ "END AS hospType,\r\n"
			+ "SUM(\r\n"
			+ "CASE\r\n"
			+ "WHEN ac.cs_apprv_rej_dt IS NOT NULL AND ag.group_id = 'CD17' THEN 1\r\n"
			+ "ELSE 0\r\n"
			+ "END\r\n"
			+ ") AS totalPreauthsApproved,\r\n"
			+ "SUM(\r\n"
			+ "CASE\r\n"
			+ "WHEN ac.cs_apprv_rej_dt IS NOT NULL AND ag.group_id = 'CD17'\r\n"
			+ "THEN DECODE(\r\n"
			+ "acc.case_cmo_aprv_amt, \r\n"
			+ "NULL, \r\n"
			+ "DECODE(\r\n"
			+ "acc.case_ceo_aprv_amt, \r\n"
			+ "NULL, \r\n"
			+ "acc.case_trust_aprv_amt, \r\n"
			+ "0, \r\n"
			+ "acc.case_trust_aprv_amt, \r\n"
			+ "acc.case_ceo_aprv_amt\r\n"
			+ "),\r\n"
			+ "acc.case_cmo_aprv_amt\r\n"
			+ ")\r\n"
			+ "ELSE 0\r\n"
			+ "END\r\n"
			+ ") AS preauthsApprovedAmount,\r\n"
			+ "SUM(\r\n"
			+ "CASE\r\n"
			+ "WHEN ac.case_status = 'CD125' THEN 1\r\n"
			+ "ELSE 0\r\n"
			+ "END\r\n"
			+ ") AS totalClaimsApproved,\r\n"
			+ "SUM(\r\n"
			+ "CASE\r\n"
			+ "WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL AND acc.case_ceo_aprv_amt IS NULL\r\n"
			+ "THEN acc.case_eo_aprv_amt\r\n"
			+ "WHEN ac.case_status = 'CD125' AND ac.cs_apprv_rej_dt IS NOT NULL\r\n"
			+ "THEN acc.case_ceo_aprv_amt\r\n"
			+ "ELSE 0\r\n"
			+ "END\r\n"
			+ ") AS claimsPaidAmount\r\n"
			+ "FROM \r\n"
			+ "asrit_case ac\r\n"
			+ "LEFT JOIN asrit_case_claim acc ON ac.case_id = acc.case_id\r\n"
			+ "LEFT JOIN asrim_case_status_grp ag ON ac.case_status = ag.status_id\r\n"
			+ "LEFT JOIN asrim_hospitals ah ON ah.hosp_id = ac.case_hosp_code\r\n"
			+ "LEFT JOIN asrit_empnl_hospinfo aeh ON ah.HOSP_EMPNL_REF_NUM = aeh.hospinfo_id\r\n"
			+ "LEFT JOIN asrim_locations dis ON dis.loc_id = ah.dist_id\r\n"
			+ "LEFT JOIN asrim_locations mand ON mand.loc_id = aeh.mandal\r\n"
			+ "LEFT JOIN splty ON splty.case_id = ac.case_id\r\n"
			+ "WHERE \r\n"
			+ "ag.group_id = 'CD17' \r\n"
			+ "AND TRUNC(ac.cs_apprv_rej_dt) = TRUNC(SYSDATE)\r\n"
			+ "GROUP BY\r\n"
			+ "TRUNC(SYSDATE),\r\n"
			+ "ac.case_hosp_code,\r\n"
			+ "splty.dis_main_code,\r\n"
			+ "ah.hosp_name,\r\n"
			+ "dis.lgd_code, dis.loc_name,\r\n"
			+ "mand.lgd_code, mand.loc_name,\r\n"
			+ "ah.hosp_type\r\n"
			+ ")\r\n"
			+ "SELECT *\r\n"
			+ "FROM cte",nativeQuery = true)
	List<PreauthDetailsResponseDto> getPreauthDetailsData();
	
	

}
